config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  
  def comment_params
    params.require(:comment).permit(
      :name,
      :comment
    )
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :update, :edit, :destroy]
  
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post  = Post.new
  end
  
  def create

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def update

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @post.destroy

    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(
      :title,
      :content
    )
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong>
            <%= comment.name %>:
          </strong>
          <%= comment.comment %>
        </p>
      </div>
    </div>

    <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: "Are you sure?" } %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
      <div class="control">
        <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>

    <%= f.button :submit, class: "button is-primary"%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-primary is-medium">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'Demo Blog', root_path, class: "navbar-item" %>
              <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <%= link_to "Create New Post", new_post_path, class:"navbar-item" %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>
    
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
  <%= simple_form_for @post do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>

    <%= f.button :submit, class: "button is-primary"%>

  <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title, "Index" %>

<section class="section">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">
                <%= link_to post.title, post %>
              </p>
            </div>
          </div>
          <div class="content">
            <%= post.content %>
          </div>
          <!--
          <div class="comment-count">
            <span class="tag is-rounded">
              <% # comment count %>
            </span>
          </div>
          -->
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
  <div class="container">
    <nav class="level">
      <!-- Left side -->
      <div class="level-left">
        <p class="level-item">
          <strong> Actions </strong>
        </p>
      </div>

      <!-- Right side -->
      <div class="level-right">
        <p class="level-item">
          <%= link_to "Edit", edit_post_path(@post), class: "button" %>
        </p>
        <p class="level-item">
          <%= link_to "Delete", post_path(@post),method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>
        </p>
      </div>
    </nav>
    <hr />

    <div class="content">
      <%= @post.content %>
    </div>
  </div>
</section>

<section class="section-comments">
  <div class="container">
    <h2 class="subtitle is-5">
      <strong>
        <%= @post.comments.count %> Comments
      </strong>
    </h2>
    <%= render @post.comments %>
    <div class="comment-form">
      <hr>
      <h3 class="subtitle is-3">
        Leave a reply
      </h3>
      <%= render 'comments/form' %>
    </div>
  </div>
</section>